language: node_js
node_js: node
cache:
  directories:
  - node_modules
before_install:
  - yarn global add greenkeeper-lockfile@1

install:
  - yarn --frozen-lockfile --non-interactive

before_script: greenkeeper-lockfile-update

script: yarn vue-cli-service lint --no-fix && yarn vue-cli-service test:unit

after_script: greenkeeper-lockfile-upload

env:
  global:
    - GK_LOCK_DEFAULT_BRANCH=develop
    - secure: EO/eikaLnXmk98wuoM3eX1Eg28e23SzxyGK2P6iLlr7kJfcNbjM5gY75UlO8knrhudxic9pT0WgyRbb29/eAOHVXiLJu8RR7eK2PRwBxSgpQfR4pgpt0klzG6dfgXW5ZE4d4wkqQvjOSCeFgX73TaT0mxM65mhRaRFu5pl38pCmCjUikTGr0aQi2EI/pO2jzUu6SMBTEj0/lhF4IEYkkFbc9GSDk+fWdPyb84rPaenWjD8au3jANwxbMroObz/ytJGeS6XjQrXLbjd08a7Czg5s8uz0EIeRpGc7pYyp88G7EB32b1MtJCj3zwT05yfCJeIEedRRWnYBbli8PMBgSVwAE3kBe3QNRURALtxtntZ1JcHDV/EB7X+RE+czcDxgotCIUZ5Yrb3vGCNpdi4v/ps2jBKaRvTzgSbGc/aIdJXq6coISuvdRRgJ6eJKk6yEeJwSJCGfmSgwJmlV4WmbY2tvW9hCpNnK+K7GIVBL4n3jVCHxKk8/t4VVRoTc8NK7d7aWCuMtXgFR/qKu0Ao7XcGBLDkc0auKSmzCEBOUXkmh9bbIx8VpUE0uIbFl2RKRsph5L9Oa9VsrJYv9Hc9m9M9Psa49xmtTFkb0bsA+gP2PE8UM+AsWuudZz6oAhnNFJ6ktPeCnZgeT+JbcLxzY+mboQqAZ5EbhPY/REgansiMM=
