language: node_js
node_js: 'node'


cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - yarn global add greenkeeper-lockfile@1
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.1
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn --frozen-lockfile --non-interactive

before_script: greenkeeper-lockfile-update

script: yarn vue-cli-service lint --no-fix && yarn vue-cli-service test:unit

after_script: greenkeeper-lockfile-upload
